<?php
declare(strict_types=1);

use think\migration\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');
        $this->table('menus')->insert([
            ['id' =>   1, 'parent_id' =>   0, 'type' => 2, 'title' => '控制台',       'name' => 'Workbench',               'path' => '/workbench',                        'component' => 'workbench/index',                    'redirect' => null,                     'icon' => 'el-icon-Odometer',       'permission' => null,                         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 1, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   0, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>   2, 'parent_id' =>   0, 'type' => 1, 'title' => '系统管理',     'name' => 'System',                  'path' => '/system',                           'component' => 'LAYOUT',                             'redirect' => null,                     'icon' => 'el-icon-Setting',        'permission' => 'system',                     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' => 900, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  10, 'parent_id' =>   2, 'type' => 2, 'title' => '管理员管理',   'name' => 'SystemAdmin',             'path' => '/system/admin',                     'component' => '/system/admin/index',                'redirect' => null,                     'icon' => 'el-icon-User',           'permission' => 'system.admin',               'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  11, 'parent_id' =>  10, 'type' => 3, 'title' => '新增',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.admin.create',        'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  12, 'parent_id' =>  10, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.admin.update',        'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  13, 'parent_id' =>  10, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.admin.delete',        'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  20, 'parent_id' =>   2, 'type' => 2, 'title' => '角色管理',     'name' => 'SystemRole',              'path' => '/system/role',                      'component' => '/system/role/index',                 'redirect' => null,                     'icon' => 'el-icon-UserFilled',     'permission' => 'system.role',                'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  21, 'parent_id' =>  20, 'type' => 3, 'title' => '新增',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.role.create',         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  22, 'parent_id' =>  20, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.role.update',         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  23, 'parent_id' =>  20, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.role.delete',         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  24, 'parent_id' =>  20, 'type' => 3, 'title' => '授权',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.role.permission',     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   4, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  30, 'parent_id' =>   2, 'type' => 2, 'title' => '部门管理',     'name' => 'SystemDepartment',        'path' => '/system/department',                'component' => '/system/department/index',           'redirect' => null,                     'icon' => 'el-icon-OfficeBuilding', 'permission' => 'system.department',          'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  31, 'parent_id' =>  30, 'type' => 3, 'title' => '新增',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.department.create',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  32, 'parent_id' =>  30, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.department.update',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  33, 'parent_id' =>  30, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.department.delete',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  40, 'parent_id' =>   2, 'type' => 2, 'title' => '权限管理',     'name' => 'SystemPermission',        'path' => '/system/permission',                'component' => '/system/permission/index',           'redirect' => null,                     'icon' => 'el-icon-Lock',           'permission' => 'system.permission',          'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   4, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  50, 'parent_id' =>   2, 'type' => 2, 'title' => '菜单管理',     'name' => 'SystemMenu',              'path' => '/system/menu',                      'component' => '/system/menu/index',                 'redirect' => null,                     'icon' => 'el-icon-Menu',           'permission' => 'system.menu',                'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   5, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  60, 'parent_id' =>   2, 'type' => 2, 'title' => '数据字典',     'name' => 'SystemDictionary',        'path' => '/system/dictionary',                'component' => '/system/dictionary/index',           'redirect' => null,                     'icon' => 'el-icon-Collection',     'permission' => 'system.dictionary',          'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   6, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  61, 'parent_id' =>  60, 'type' => 3, 'title' => '新增',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.dictionary.create',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  62, 'parent_id' =>  60, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.dictionary.update',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  63, 'parent_id' =>  60, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.dictionary.delete',   'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  70, 'parent_id' =>   2, 'type' => 2, 'title' => '文件管理',     'name' => 'SystemFile',              'path' => '/system/file',                      'component' => '/system/file/index',                 'redirect' => null,                     'icon' => 'el-icon-FolderOpened',   'permission' => 'system.file',                'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   7, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  71, 'parent_id' =>  70, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.file.delete',         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  80, 'parent_id' =>   2, 'type' => 2, 'title' => '通知管理',     'name' => 'SystemNotification',      'path' => '/system/notification',              'component' => '/system/notification/index',         'redirect' => null,                     'icon' => 'el-icon-Bell',           'permission' => 'system.notification',        'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   8, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  81, 'parent_id' =>  80, 'type' => 3, 'title' => '发布',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.notification.create', 'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  82, 'parent_id' =>  80, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.notification.update', 'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  83, 'parent_id' =>  80, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.notification.delete', 'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  90, 'parent_id' =>   2, 'type' => 2, 'title' => '定时任务',     'name' => 'SystemCronJob',           'path' => '/system/cron-job',                  'component' => '/system/cron-job/index',             'redirect' => null,                     'icon' => 'el-icon-Timer',          'permission' => 'system.cron_job',            'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   9, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  91, 'parent_id' =>  90, 'type' => 3, 'title' => '新增',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.cron_job.create',     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  92, 'parent_id' =>  90, 'type' => 3, 'title' => '编辑',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.cron_job.update',     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  93, 'parent_id' =>  90, 'type' => 3, 'title' => '删除',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.cron_job.delete',     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>  94, 'parent_id' =>  90, 'type' => 3, 'title' => '执行',         'name' => null,                      'path' => null,                                'component' => null,                                 'redirect' => null,                     'icon' => null,                     'permission' => 'system.cron_job.run',        'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   4, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 100, 'parent_id' =>   2, 'type' => 2, 'title' => '系统配置',     'name' => 'SystemConfig',            'path' => '/system/config',                    'component' => '/system/config/index',               'redirect' => null,                     'icon' => 'el-icon-Tools',          'permission' => 'system.config',              'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>  10, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 110, 'parent_id' =>   2, 'type' => 1, 'title' => '日志管理',     'name' => 'SystemLog',               'path' => '/system/log',                       'component' => 'LAYOUT',                             'redirect' => null,                     'icon' => 'el-icon-Document',       'permission' => 'system.log',                 'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>  11, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 111, 'parent_id' => 110, 'type' => 2, 'title' => '登录日志',     'name' => 'SystemLoginLog',          'path' => '/system/log/login',                 'component' => '/system/log/login',                  'redirect' => null,                     'icon' => null,                     'permission' => 'system.log.login',           'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 112, 'parent_id' => 110, 'type' => 2, 'title' => '操作日志',     'name' => 'SystemOperationLog',      'path' => '/system/log/operation',             'component' => '/system/log/operation',              'redirect' => null,                     'icon' => null,                     'permission' => 'system.log.operation',       'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>   3, 'parent_id' =>   0, 'type' => 1, 'title' => '开发工具',     'name' => 'DevTools',                'path' => '/dev-tools',                        'component' => 'LAYOUT',                             'redirect' => null,                     'icon' => 'el-icon-Cpu',            'permission' => null,                         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' => 950, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 200, 'parent_id' =>   3, 'type' => 2, 'title' => '代码生成器',   'name' => 'DevGenerator',            'path' => '/dev-tools/generator',              'component' => '/system/generator/index',            'redirect' => null,                     'icon' => 'el-icon-MagicStick',     'permission' => 'system.generator',           'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 210, 'parent_id' =>   3, 'type' => 2, 'title' => 'API文档',      'name' => 'DevApiDoc',               'path' => '/dev-tools/api-doc',                'component' => '/system/api-doc/index',              'redirect' => null,                     'icon' => 'el-icon-Notebook',       'permission' => 'system.api_doc',             'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 120, 'parent_id' =>   2, 'type' => 1, 'title' => '消息管理',     'name' => 'SystemMessage',           'path' => '/system/message',                   'component' => 'LAYOUT',                             'redirect' => '/system/message/template', 'icon' => 'el-icon-ChatDotRound',   'permission' => 'system.message',             'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>  12, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 121, 'parent_id' => 120, 'type' => 2, 'title' => '消息模板',     'name' => 'SystemMessageTemplate',   'path' => '/system/message/template',          'component' => '/system/message/template/index',     'redirect' => null,                     'icon' => 'el-icon-Tickets',        'permission' => 'system.message.template',    'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 122, 'parent_id' => 120, 'type' => 2, 'title' => '发送记录',     'name' => 'SystemMessageLog',        'path' => '/system/message/log',               'component' => '/system/message/log/index',          'redirect' => null,                     'icon' => 'el-icon-List',           'permission' => 'system.message.log',         'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>   4, 'parent_id' =>   0, 'type' => 1, 'title' => '渠道管理',     'name' => 'Channel',                 'path' => '/channel',                          'component' => 'LAYOUT',                             'redirect' => '/channel/official/config', 'icon' => 'el-icon-Promotion',      'permission' => 'channel',                    'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' => 700, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>   5, 'parent_id' =>   4, 'type' => 1, 'title' => '公众号',       'name' => 'ChannelOfficial',         'path' => '/channel/official',                 'component' => 'LAYOUT',                             'redirect' => '/channel/official/config', 'icon' => 'el-icon-Service',        'permission' => 'channel.official',           'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 400, 'parent_id' =>   5, 'type' => 2, 'title' => '公众号配置',   'name' => 'ChannelOfficialConfig',   'path' => '/channel/official/config',          'component' => '/channel/official/config',           'redirect' => null,                     'icon' => 'el-icon-Setting',        'permission' => 'channel.official.config',    'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 410, 'parent_id' =>   5, 'type' => 2, 'title' => '自定义菜单',   'name' => 'ChannelOfficialMenu',     'path' => '/channel/official/menu',            'component' => '/channel/official/menu',             'redirect' => null,                     'icon' => 'el-icon-Grid',           'permission' => 'channel.official.menu',      'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 420, 'parent_id' =>   5, 'type' => 2, 'title' => '自动回复',     'name' => 'ChannelAutoReply',        'path' => '/channel/official/auto-reply',      'component' => '/channel/official/auto-reply',       'redirect' => null,                     'icon' => 'el-icon-ChatSquare',     'permission' => 'channel.official.auto_reply', 'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   3, 'created_at' => $now, 'updated_at' => $now],
            ['id' =>   6, 'parent_id' =>   4, 'type' => 1, 'title' => '小程序',       'name' => 'ChannelMiniApp',          'path' => '/channel/miniapp',                  'component' => 'LAYOUT',                             'redirect' => '/channel/miniapp/config',  'icon' => 'el-icon-Iphone',         'permission' => 'channel.miniapp',            'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   2, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 500, 'parent_id' =>   6, 'type' => 2, 'title' => '小程序配置',   'name' => 'ChannelMiniAppConfig',    'path' => '/channel/miniapp/config',           'component' => '/channel/miniapp/config',            'redirect' => null,                     'icon' => 'el-icon-Setting',        'permission' => 'channel.miniapp.config',     'is_hidden' => 0, 'is_cache' => 1, 'is_affix' => 0, 'is_iframe' => 0, 'external_link' => null, 'breadcrumb' => 1, 'active_menu' => null, 'meta' => null, 'status' => 1, 'sort' =>   1, 'created_at' => $now, 'updated_at' => $now],
        ])->saveData();

        // Assign all permissions to super admin role (role_id=1)
        $this->getAdapter()->execute(
            "INSERT INTO role_permissions (role_id, permission_id, created_at, updated_at) SELECT 1, id, NOW(), NOW() FROM permissions"
        );

        // Assign all menus to super admin role (role_id=1)
        $this->getAdapter()->execute(
            "INSERT INTO role_menus (role_id, menu_id, created_at, updated_at) SELECT 1, id, NOW(), NOW() FROM menus"
        );
    }
}
