<?php
declare(strict_types=1);

use think\migration\Seeder;

class SystemConfigSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $this->table('system_configs')->insert([
            // ── Basic ────────────────────────────────────────────────────────────
            ['config_key' => 'site_name',              'config_value' => '元点Admin',                                                                                                         'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '网站名称',        'config_desc' => '显示在浏览器标题栏和系统Logo旁',                           'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_url',               'config_value' => 'http://localhost',                                                                                                  'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '网站地址',        'config_desc' => '网站访问地址，用于生成完整链接',                           'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_logo',              'config_value' => '/storage/uploads/images/logo.png',                                                                                  'config_group' => 'basic',           'config_type' => 'file',    'config_name' => '网站Logo',        'config_desc' => '建议尺寸 200x50，支持 PNG/SVG 格式',                       'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_favicon',           'config_value' => '/storage/uploads/images/favicon.ico',                                                                               'config_group' => 'basic',           'config_type' => 'file',    'config_name' => '网站图标',        'config_desc' => '浏览器标签页图标，建议 32x32 ICO/PNG 格式',               'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_description',       'config_value' => '一款通用的后台管理系统',                                                                                            'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '网站描述',        'config_desc' => '用于SEO和网站简介',                                        'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  5, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_keywords',          'config_value' => '后台管理,管理系统,Admin',                                                                                           'config_group' => 'basic',           'config_type' => 'string',  'config_name' => 'SEO关键词',       'config_desc' => '多个关键词用英文逗号分隔',                                 'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  6, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_icp',               'config_value' => '',                                                                                                                  'config_group' => 'basic',           'config_type' => 'string',  'config_name' => 'ICP备案号',       'config_desc' => '如：京ICP备XXXXXXXX号',                                    'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  7, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_copyright',         'config_value' => 'Copyright © 2024 Dev007. All rights reserved.',                                                                     'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '版权信息',        'config_desc' => '显示在页面底部的版权声明',                                 'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  8, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_phone',             'config_value' => '',                                                                                                                  'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '联系电话',        'config_desc' => '网站管理员联系电话',                                       'config_options' => null, 'config_depends' => null,                                        'sort_order' =>  9, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_email',             'config_value' => '',                                                                                                                  'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '联系邮箱',        'config_desc' => '网站管理员联系邮箱',                                       'config_options' => null, 'config_depends' => null,                                        'sort_order' => 10, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_address',           'config_value' => '',                                                                                                                  'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '联系地址',        'config_desc' => '公司或团队地址',                                           'config_options' => null, 'config_depends' => null,                                        'sort_order' => 11, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_status',            'config_value' => '1',                                                                                                                 'config_group' => 'basic',           'config_type' => 'boolean', 'config_name' => '网站开关',        'config_desc' => '关闭后前台将显示维护提示',                                 'config_options' => null, 'config_depends' => null,                                        'sort_order' => 12, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'site_close_tip',         'config_value' => '网站维护中，请稍后再试...',                                                                                         'config_group' => 'basic',           'config_type' => 'string',  'config_name' => '关闭提示',        'config_desc' => '网站关闭时显示的提示信息',                                 'config_options' => null, 'config_depends' => null,                                        'sort_order' => 13, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'user_register',          'config_value' => '1',                                                                                                                 'config_group' => 'basic',           'config_type' => 'boolean', 'config_name' => '开放注册',        'config_desc' => '是否允许新用户注册',                                       'config_options' => null, 'config_depends' => null,                                        'sort_order' => 14, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'login_captcha',          'config_value' => '1',                                                                                                                 'config_group' => 'basic',           'config_type' => 'boolean', 'config_name' => '登录验证码',      'config_desc' => '登录时是否需要输入验证码',                                 'config_options' => null, 'config_depends' => null,                                        'sort_order' => 15, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'password_min_length',    'config_value' => '6',                                                                                                                 'config_group' => 'basic',           'config_type' => 'number',  'config_name' => '密码最小长度',    'config_desc' => '用户密码最少字符数',                                       'config_options' => null, 'config_depends' => null,                                        'sort_order' => 16, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'login_max_retry',        'config_value' => '5',                                                                                                                 'config_group' => 'basic',           'config_type' => 'number',  'config_name' => '登录失败上限',    'config_desc' => '连续登录失败后锁定账号的次数',                             'config_options' => null, 'config_depends' => null,                                        'sort_order' => 17, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'login_lock_duration',    'config_value' => '30',                                                                                                                'config_group' => 'basic',           'config_type' => 'number',  'config_name' => '锁定时长(分钟)',  'config_desc' => '账号被锁定后的等待时间',                                   'config_options' => null, 'config_depends' => null,                                        'sort_order' => 18, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── Email ────────────────────────────────────────────────────────────
            ['config_key' => 'smtp_host',              'config_value' => '',                                                                                                                  'config_group' => 'email',           'config_type' => 'string',  'config_name' => 'SMTP服务器',      'config_desc' => '例如：smtp.qq.com、smtp.163.com',                          'config_options' => null,                                'config_depends' => null, 'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_port',              'config_value' => '465',                                                                                                               'config_group' => 'email',           'config_type' => 'number',  'config_name' => 'SMTP端口',        'config_desc' => '常用端口：25(不加密)、465(SSL)、587(TLS)',                 'config_options' => null,                                'config_depends' => null, 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_user',              'config_value' => '',                                                                                                                  'config_group' => 'email',           'config_type' => 'string',  'config_name' => 'SMTP用户名',      'config_desc' => '通常为发件人邮箱地址',                                     'config_options' => null,                                'config_depends' => null, 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_pass',              'config_value' => '',                                                                                                                  'config_group' => 'email',           'config_type' => 'string',  'config_name' => 'SMTP密码',        'config_desc' => 'SMTP授权码或密码',                                         'config_options' => null,                                'config_depends' => null, 'sort_order' =>  4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_from_address',      'config_value' => '',                                                                                                                  'config_group' => 'email',           'config_type' => 'string',  'config_name' => '发件人地址',      'config_desc' => '发件人邮箱地址',                                           'config_options' => null,                                'config_depends' => null, 'sort_order' =>  5, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_from_name',         'config_value' => '元点Admin',                                                                                                        'config_group' => 'email',           'config_type' => 'string',  'config_name' => '发件人名称',      'config_desc' => '收件人看到的发件人名称',                                   'config_options' => null,                                'config_depends' => null, 'sort_order' =>  6, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'smtp_encryption',        'config_value' => 'ssl',                                                                                                               'config_group' => 'email',           'config_type' => 'select',  'config_name' => '加密方式',        'config_desc' => '邮件传输加密方式',                                         'config_options' => '{"ssl":"SSL","tls":"TLS","none":"不加密"}', 'config_depends' => null, 'sort_order' =>  7, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'email_test_address',     'config_value' => '',                                                                                                                  'config_group' => 'email',           'config_type' => 'string',  'config_name' => '测试收件地址',    'config_desc' => '用于发送测试邮件的收件人地址',                             'config_options' => null,                                'config_depends' => null, 'sort_order' =>  8, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── SMS ──────────────────────────────────────────────────────────────
            ['config_key' => 'sms_driver',             'config_value' => 'aliyun',                                                                                                            'config_group' => 'sms',             'config_type' => 'select',  'config_name' => '短信服务商',      'config_desc' => '选择短信发送服务商',                                       'config_options' => '{"aliyun":"阿里云","tencent":"腾讯云"}', 'config_depends' => null, 'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'sms_access_key',         'config_value' => '',                                                                                                                  'config_group' => 'sms',             'config_type' => 'string',  'config_name' => 'AccessKey ID',    'config_desc' => '短信服务商提供的 AccessKey ID',                            'config_options' => null,                                'config_depends' => null, 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'sms_access_secret',      'config_value' => '',                                                                                                                  'config_group' => 'sms',             'config_type' => 'string',  'config_name' => 'AccessKey Secret','config_desc' => '短信服务商提供的 AccessKey Secret',                        'config_options' => null,                                'config_depends' => null, 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'sms_sign_name',          'config_value' => '',                                                                                                                  'config_group' => 'sms',             'config_type' => 'string',  'config_name' => '短信签名',        'config_desc' => '已审核通过的短信签名',                                     'config_options' => null,                                'config_depends' => null, 'sort_order' =>  4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── Payment ──────────────────────────────────────────────────────────
            ['config_key' => 'pay_alipay_enabled',        'config_value' => '0', 'config_group' => 'payment', 'config_type' => 'boolean', 'config_name' => '启用支付宝',       'config_desc' => '是否开启支付宝支付',                                  'config_options' => null, 'config_depends' => null,                                             'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_alipay_app_id',         'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '支付宝AppID',      'config_desc' => '支付宝开放平台应用AppID',                             'config_options' => null, 'config_depends' => '{"field":"pay_alipay_enabled","value":"1"}', 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_alipay_private_key',    'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '应用私钥',         'config_desc' => '支付宝应用私钥(RSA2)',                                'config_options' => null, 'config_depends' => '{"field":"pay_alipay_enabled","value":"1"}', 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_alipay_public_key',     'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '支付宝公钥',       'config_desc' => '支付宝公钥',                                          'config_options' => null, 'config_depends' => '{"field":"pay_alipay_enabled","value":"1"}', 'sort_order' =>  4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_alipay_notify_url',     'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '异步通知地址',     'config_desc' => '支付宝异步回调通知URL',                               'config_options' => null, 'config_depends' => '{"field":"pay_alipay_enabled","value":"1"}', 'sort_order' =>  5, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_enabled',        'config_value' => '0', 'config_group' => 'payment', 'config_type' => 'boolean', 'config_name' => '启用微信支付',     'config_desc' => '是否开启微信支付',                                    'config_options' => null, 'config_depends' => null,                                             'sort_order' =>  6, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_app_id',         'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信AppID',        'config_desc' => '微信公众号或小程序AppID',                             'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' =>  7, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_mch_id',         'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信商户号',       'config_desc' => '微信支付商户号',                                      'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' =>  8, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_api_key',        'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信API密钥',      'config_desc' => '微信支付APIv3密钥',                                   'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' =>  9, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_api_v3_key',     'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信APIv3密钥',    'config_desc' => '微信支付APIv3密钥（用于V3接口）',                     'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' => 10, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_serial_no',      'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信证书序列号',   'config_desc' => '微信支付平台证书序列号',                              'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' => 11, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_private_key_path','config_value' => '', 'config_group' => 'payment', 'config_type' => 'string',  'config_name' => '微信私钥文件',     'config_desc' => '商户API私钥文件路径（apiclient_key.pem）',            'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' => 12, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_cert_path',      'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '微信证书文件',     'config_desc' => '商户API证书文件路径（apiclient_cert.pem）',           'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' => 13, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'pay_wechat_notify_url',     'config_value' => '', 'config_group'  => 'payment', 'config_type' => 'string',  'config_name' => '异步通知地址',     'config_desc' => '微信支付异步回调通知URL',                             'config_options' => null, 'config_depends' => '{"field":"pay_wechat_enabled","value":"1"}', 'sort_order' => 14, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── Storage (local + common) ──────────────────────────────────────────
            ['config_key' => 'storage_driver',             'config_value' => 'local', 'config_group' => 'storage', 'config_type' => 'select',  'config_name' => '存储方式',          'config_desc' => '选择文件存储方式',                                                                    'config_options' => '{"local":"本地存储","aliyun":"阿里云OSS","tencent":"腾讯云COS","qiniu":"七牛云"}', 'config_depends' => null,                                                 'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_upload_max_size',    'config_value' => '10',    'config_group' => 'storage', 'config_type' => 'number',  'config_name' => '最大上传(MB)',      'config_desc' => '单个文件最大上传大小，单位MB',                                                        'config_options' => null,                                                                             'config_depends' => null,                                                 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_upload_allowed_ext', 'config_value' => 'jpg,jpeg,png,gif,svg,webp,bmp,doc,docx,xls,xlsx,ppt,pptx,pdf,zip,rar,txt,csv', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => '允许的文件类型', 'config_desc' => '允许上传的文件扩展名，英文逗号分隔', 'config_options' => null,                                                                             'config_depends' => null,                                                 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_image_max_size',     'config_value' => '5',     'config_group' => 'storage', 'config_type' => 'number',  'config_name' => '图片最大(MB)',      'config_desc' => '单张图片最大上传大小，单位MB',                                                        'config_options' => null,                                                                             'config_depends' => null,                                                 'sort_order' =>  4, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Aliyun OSS
            ['config_key' => 'storage_oss_access_key',    'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'OSS AccessKey',    'config_desc' => '阿里云OSS AccessKey ID',                                     'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"aliyun"}',  'sort_order' => 10, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_oss_access_secret', 'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'OSS AccessSecret', 'config_desc' => '阿里云OSS AccessKey Secret',                                 'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"aliyun"}',  'sort_order' => 11, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_oss_bucket',        'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'OSS Bucket',       'config_desc' => '阿里云OSS Bucket名称',                                       'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"aliyun"}',  'sort_order' => 12, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_oss_endpoint',      'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'OSS Endpoint',     'config_desc' => '阿里云OSS 访问域名，如 oss-cn-hangzhou.aliyuncs.com',        'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"aliyun"}',  'sort_order' => 13, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_oss_domain',        'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'OSS 自定义域名',   'config_desc' => '绑定的自定义域名，用于生成访问URL',                          'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"aliyun"}',  'sort_order' => 14, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Tencent COS
            ['config_key' => 'storage_cos_secret_id',     'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'COS SecretId',     'config_desc' => '腾讯云COS SecretId',                                         'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"tencent"}', 'sort_order' => 20, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_cos_secret_key',    'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'COS SecretKey',    'config_desc' => '腾讯云COS SecretKey',                                        'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"tencent"}', 'sort_order' => 21, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_cos_bucket',        'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'COS Bucket',       'config_desc' => '腾讯云COS Bucket名称（含AppId后缀，如 bucket-1250000000）', 'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"tencent"}', 'sort_order' => 22, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_cos_region',        'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'COS Region',       'config_desc' => '腾讯云COS 地域，如 ap-guangzhou',                            'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"tencent"}', 'sort_order' => 23, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_cos_domain',        'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => 'COS 自定义域名',   'config_desc' => '绑定的自定义域名，用于生成访问URL',                          'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"tencent"}', 'sort_order' => 24, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            // Qiniu
            ['config_key' => 'storage_qiniu_access_key',  'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => '七牛 AccessKey',   'config_desc' => '七牛云 AccessKey',                                           'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"qiniu"}',   'sort_order' => 30, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_qiniu_secret_key',  'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => '七牛 SecretKey',   'config_desc' => '七牛云 SecretKey',                                           'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"qiniu"}',   'sort_order' => 31, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_qiniu_bucket',      'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => '七牛 Bucket',      'config_desc' => '七牛云存储空间名称',                                         'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"qiniu"}',   'sort_order' => 32, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'storage_qiniu_domain',      'config_value' => '', 'config_group' => 'storage', 'config_type' => 'string', 'config_name' => '七牛访问域名',     'config_desc' => '七牛云存储空间绑定的域名（含协议，如 https://cdn.example.com）', 'config_options' => null, 'config_depends' => '{"field":"storage_driver","value":"qiniu"}', 'sort_order' => 33, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── WeChat Official ───────────────────────────────────────────────────
            ['config_key' => 'wechat_official_name',        'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => '公众号名称',      'config_desc' => '微信公众号名称',                             'config_options' => null, 'config_depends' => null, 'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_original_id', 'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => '原始ID',          'config_desc' => '公众号原始ID，如 gh_xxxxxxxx',               'config_options' => null, 'config_depends' => null, 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_qrcode',      'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'file',   'config_name' => '公众号二维码',    'config_desc' => '公众号二维码图片，建议 200x200',             'config_options' => null, 'config_depends' => null, 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_app_id',      'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => 'AppID',           'config_desc' => '微信公众号AppID（开发者ID）',                'config_options' => null, 'config_depends' => null, 'sort_order' => 10, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_app_secret',  'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => 'AppSecret',       'config_desc' => '微信公众号AppSecret（开发者密码）',          'config_options' => null, 'config_depends' => null, 'sort_order' => 11, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_token',       'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => 'Token',           'config_desc' => '微信公众号消息校验Token',                    'config_options' => null, 'config_depends' => null, 'sort_order' => 20, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_official_aes_key',     'config_value' => '', 'config_group' => 'wechat_official', 'config_type' => 'string', 'config_name' => 'EncodingAESKey',  'config_desc' => '微信公众号消息加解密密钥（43位字符）',       'config_options' => null, 'config_depends' => null, 'sort_order' => 21, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── WeChat Open Platform ─────────────────────────────────────────────
            ['config_key' => 'wechat_open_app_id',     'config_value' => '', 'config_group' => 'wechat_open', 'config_type' => 'string', 'config_name' => 'AppID',     'config_desc' => '微信开放平台网站应用AppID',     'config_options' => null, 'config_depends' => null, 'sort_order' => 1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_open_app_secret', 'config_value' => '', 'config_group' => 'wechat_open', 'config_type' => 'string', 'config_name' => 'AppSecret', 'config_desc' => '微信开放平台网站应用AppSecret', 'config_options' => null, 'config_depends' => null, 'sort_order' => 2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],

            // ── WeChat Mini ───────────────────────────────────────────────────────
            ['config_key' => 'wechat_mini_name',        'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => '小程序名称',      'config_desc' => '微信小程序名称',                             'config_options' => null,                            'config_depends' => null, 'sort_order' =>  1, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_original_id', 'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => '原始ID',          'config_desc' => '小程序原始ID，如 gh_xxxxxxxx',               'config_options' => null,                            'config_depends' => null, 'sort_order' =>  2, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_qrcode',      'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'file',   'config_name' => '小程序二维码',    'config_desc' => '小程序二维码图片，建议 200x200',             'config_options' => null,                            'config_depends' => null, 'sort_order' =>  3, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_app_id',      'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => 'AppID',           'config_desc' => '微信小程序AppID',                            'config_options' => null,                            'config_depends' => null, 'sort_order' => 10, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_app_secret',  'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => 'AppSecret',       'config_desc' => '微信小程序AppSecret',                        'config_options' => null,                            'config_depends' => null, 'sort_order' => 11, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_msg_token',   'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => 'Token',           'config_desc' => '消息推送校验Token',                          'config_options' => null,                            'config_depends' => null, 'sort_order' => 20, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_msg_aes_key', 'config_value' => '',     'config_group' => 'wechat_mini', 'config_type' => 'string', 'config_name' => 'EncodingAESKey',  'config_desc' => '消息推送加解密密钥（43位字符）',             'config_options' => null,                            'config_depends' => null, 'sort_order' => 21, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['config_key' => 'wechat_mini_msg_format',  'config_value' => 'JSON', 'config_group' => 'wechat_mini', 'config_type' => 'select', 'config_name' => '数据格式',        'config_desc' => '消息推送数据格式',                           'config_options' => '{"JSON":"JSON","XML":"XML"}',   'config_depends' => null, 'sort_order' => 22, 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
        ])->saveData();

        // ── Cron Jobs ─────────────────────────────────────────────────────────────
        $this->table('cron_jobs')->insert([
            ['name' => '清理过期管理员日志', 'command' => 'log:archive', 'expression' => '0 3 * * *', 'description' => '每天凌晨3点归档清理过期管理员操作日志', 'status' => 1, 'created_at' => $now, 'updated_at' => $now],
        ])->saveData();
    }
}
